#!/usr/bin/env bun
import path from "node:path";
import { existsSync } from "node:fs";
import {
  REPO_ROOT,
  ID_REGEX,
  loadJson,
  loadSchema,
  makeAjv,
  sha256File,
  walkFiles,
} from "./lib";
import { unknownParameterKeys } from "./parameter-dictionary";
import {
  runComponentGates,
  runFootprintGates,
  type GateComponent,
  type GateFootprint,
  type GateSymbol,
} from "./gates/run-gates";
import type { GateFinding } from "./gates/types";

interface Issue {
  file: string;
  message: string;
}

interface Provenance {
  source?: string;
  license?: string;
  attribution?: string[];
  sourceFormat?: string;
  sourceFileName?: string;
  sourceLibrary?: string;
  sourceItemName?: string;
  sourceHash?: string;
  upstreamUrl?: string;
  upstreamCommit?: string;
  convertedAt?: string;
  conversionTool?: string;
}

interface PinMapEntry {
  pinNumber: string;
  padNumber: string;
  pinName?: string;
}

interface PointMm {
  x: number;
  y: number;
}

interface SymbolSource {
  id: string;
  uuid: string;
  provenance: Provenance;
  raw?: unknown;
  normalized?: {
    pins?: Array<{
      number?: string;
      unit?: number;
      name?: string;
      originPinKey?: string;
      localPosition?: PointMm;
    }>;
    preview?: {
      unitCount?: number;
      pins?: Array<{ number?: string; unit?: number; id?: string; anchor?: PointMm }>;
      labels?: Array<{ fontSizeMm?: number; text?: string }>;
    };
  };
}

interface FootprintSource {
  id: string;
  uuid: string;
  name?: string;
  provenance: Provenance;
  models3d?: string[];
  no3d?: boolean;
  raw?: unknown;
  normalized?: {
    preview?: {
      pads?: Array<{ number?: string }>;
      graphics?: Array<{ layer?: string }>;
    };
  };
}

const issues: Issue[] = [];
const warnings: Issue[] = [];
const flags = new Set(process.argv.slice(2));
const STRICT = flags.has("--strict") || flags.has("--release");
const REQUIRE_STEP_3D =
  flags.has("--require-step-3d") || flags.has("--release");
const LIBRARY_ROOT = process.env.CORELIB_ROOT
  ? path.resolve(process.env.CORELIB_ROOT)
  : REPO_ROOT;

const REQUIRED_KICAD_PROVENANCE_FIELDS = [
  "source",
  "license",
  "attribution",
  "sourceFormat",
  "sourceFileName",
  "sourceLibrary",
  "sourceItemName",
  "sourceHash",
  "upstreamUrl",
  "convertedAt",
  "conversionTool",
] as const;

const KICAD_LICENSE = "CC-BY-SA-4.0+KiCad-Libraries-Exception";
const INCOMPATIBLE_KICAD_LICENSES = new Set(["CC-BY-4.0", "CC0-1.0"]);
// Non-KiCad asset sources (symbols/STEP authored or generated by OpenPCB, or
// redistributable manufacturer 3D). These fill the same full provenance record
// as KiCad-derived assets, but carry their own license rules (see checkProvenance).
const GENERATED_LICENSE = "CC-BY-SA-4.0";
const COMPATIBLE_GENERATED_LICENSES = new Set([
  GENERATED_LICENSE,
  KICAD_LICENSE,
]);
function fail(file: string, message: string) {
  issues.push({ file: displayPath(file), message });
}

function warn(file: string, message: string) {
  const issue = { file: displayPath(file), message };
  if (STRICT) issues.push(issue);
  else warnings.push(issue);
}

function warnDisplay(file: string, message: string) {
  const issue = { file, message };
  if (STRICT) issues.push(issue);
  else warnings.push(issue);
}

// Advisory note: always informational, never escalates to a failure under --strict.
function note(file: string, message: string) {
  warnings.push({ file: displayPath(file), message });
}

// G6–G12 live in tools/gates/*; each finding carries its own severity.
// `fail` is always fatal, `warn` is fatal under --strict, `note` never is.
function reportFindings(file: string, findings: GateFinding[]): void {
  for (const f of findings) {
    const message = `${f.gate}: ${f.message}`;
    if (f.severity === "fail") fail(file, message);
    else if (f.severity === "warn") warn(file, message);
    else note(file, message);
  }
}

function isHttpUri(value: string): boolean {
  try {
    const url = new URL(value);
    return url.protocol === "http:" || url.protocol === "https:";
  } catch {
    return false;
  }
}

function displayPath(absPath: string): string {
  return path.relative(LIBRARY_ROOT, absPath).split(path.sep).join("/");
}

function hasValue(value: unknown): boolean {
  if (typeof value === "string") return value.trim().length > 0;
  if (Array.isArray(value)) return true;
  return value !== undefined && value !== null;
}

function checkProvenance(file: string, provenance: Provenance) {
  const source = provenance.source;

  // Non-KiCad carve-out: OpenPCB-authored/generated assets and redistributable
  // manufacturer 3D. Same full provenance record is required; only the license
  // rule differs. (Truly-unknown sources still fall through untouched below.)
  if (source === "openpcb-generated" || source === "manufacturer") {
    for (const field of REQUIRED_KICAD_PROVENANCE_FIELDS) {
      if (!hasValue(provenance[field]))
        fail(file, `missing provenance field for ${source} asset: ${field}`);
    }
    if (
      Array.isArray(provenance.attribution) &&
      provenance.attribution.length === 0
    )
      warn(file, `${source} asset has empty attribution`);

    if (source === "openpcb-generated") {
      if (!COMPATIBLE_GENERATED_LICENSES.has(provenance.license ?? ""))
        fail(
          file,
          `openpcb-generated asset must be ${GENERATED_LICENSE} (or the KiCad exception), got: ${provenance.license ?? "<missing>"}`,
        );
    } else {
      if (!hasValue(provenance.license))
        fail(file, "manufacturer asset must declare a license");
      else if (INCOMPATIBLE_KICAD_LICENSES.has(provenance.license ?? ""))
        fail(
          file,
          `manufacturer asset uses a copyleft-incompatible license: ${provenance.license}`,
        );
      // Third-party-licensed but redistributable — surface for aggregate-license review.
      note(
        file,
        `manufacturer-sourced asset under third-party license '${provenance.license ?? "<missing>"}' — verify redistribution rights`,
      );
    }
    return;
  }

  if (source !== "kicad-derived") return;

  for (const field of REQUIRED_KICAD_PROVENANCE_FIELDS) {
    if (!hasValue(provenance[field]))
      fail(file, `missing KiCad provenance field: ${field}`);
  }

  if (provenance.license !== KICAD_LICENSE) {
    const reason = INCOMPATIBLE_KICAD_LICENSES.has(provenance.license ?? "")
      ? "weak conflicting license"
      : "non-CC-BY-SA compatible license";
    fail(
      file,
      `KiCad-derived asset uses ${reason}: ${provenance.license ?? "<missing>"}`,
    );
  }

  if (
    Array.isArray(provenance.attribution) &&
    provenance.attribution.length === 0
  ) {
    warn(file, "KiCad-derived asset has empty attribution");
  }
}

const ajv = makeAjv();
const validateSymbol = ajv.compile(loadSchema("symbol"));
const validateFootprint = ajv.compile(loadSchema("footprint"));
const validateComponent = ajv.compile(loadSchema("component"));
const validateModel3d = ajv.compile(loadSchema("model3d"));

const symbolsRoot = path.join(LIBRARY_ROOT, "symbols");
const footprintsRoot = path.join(LIBRARY_ROOT, "footprints");
const componentsRoot = path.join(LIBRARY_ROOT, "components");
const modelsRoot = path.join(LIBRARY_ROOT, "3d");

const uuidIndex = new Map<string, string>();
const idIndex = new Map<string, string>();

function checkUniqueness(file: string, id: string, uuid: string) {
  if (!ID_REGEX.test(id)) fail(file, `invalid id: ${id}`);
  const idHit = idIndex.get(id);
  if (idHit) fail(file, `duplicate id ${id} (also in ${idHit})`);
  else idIndex.set(id, displayPath(file));
  const uuidHit = uuidIndex.get(uuid);
  if (uuidHit) fail(file, `duplicate uuid ${uuid} (also in ${uuidHit})`);
  else uuidIndex.set(uuid, displayPath(file));
}

function stringSet(values: Array<string | undefined> | undefined): Set<string> {
  return new Set(
    (values ?? []).filter(
      (value): value is string =>
        typeof value === "string" && value.trim().length > 0,
    ),
  );
}

function symbolPinNumbers(data: SymbolSource): Set<string> {
  const normalizedPins = stringSet(
    data.normalized?.pins?.map((pin) => pin.number),
  );
  if (normalizedPins.size > 0) return normalizedPins;
  return stringSet(data.normalized?.preview?.pins?.map((pin) => pin.number));
}

function symbolPins(
  data: SymbolSource,
): Array<{ number?: string; unit?: number }> {
  if ((data.normalized?.pins ?? []).length > 0) return data.normalized!.pins!;
  return data.normalized?.preview?.pins ?? [];
}

function checkDuplicateSymbolPins(file: string, data: SymbolSource): void {
  const seen = new Set<string>();
  for (const [index, pin] of symbolPins(data).entries()) {
    const number = pin.number?.trim();
    if (!number) continue;
    const key = number;
    if (seen.has(key)) fail(file, `duplicate symbol pin number ${key}`);
    else seen.add(key);
    if (index > 1024) fail(file, "symbol has suspiciously many pins");
  }
}

function footprintPadNumbers(data: FootprintSource): Set<string> {
  return stringSet(data.normalized?.preview?.pads?.map((pad) => pad.number));
}

/**
 * Symbols whose `raw` legitimately predates the KiCad importer.
 *
 * These are OpenPCB-original 2-pin generics drawn ANSI-style (zig-zag body,
 * pins at ±5.08mm, `originPinKey` `pin-1`/`pin-2`). KiCad does ship `Device:R`
 * and `Device:C`, so an upstream parse is *available* — but adopting it is a
 * breaking change, not a cleanup: those symbols are IEC rectangles with pins at
 * ±3.81mm and `originPinKey` `u1:1`. `place-part` snapshots `originPinKey` and
 * both pin coordinates into `designer_*` at placement time, `(partId,
 * originPinKey)` is unique-indexed, and nets are unioned by world position — so
 * re-sourcing these two would strand every already-placed resistor and
 * capacitor and put newly placed ones on different coordinates than their
 * neighbours in the same schematic.
 *
 * Hand-authoring a `raw` instead would fabricate the faithful upstream parse
 * that G2 exists to guarantee, so that is worse than the exemption.
 *
 * The real cost is that `tools/rebuild-previews.ts` cannot regenerate these two
 * if preview generation changes upstream. That is currently inert: every label
 * on both sits at 1.27mm, above the app's `STALE_FONT_THRESHOLD_MM` of 1.0, so
 * `migrate-preview-models.ts` never rebuilds them client-side either. Revisit
 * only alongside a deliberate symbol-geometry migration.
 *
 * Keep this list closed — everything else must carry a real parse.
 */
const RAW_EXEMPT_SYMBOLS = new Set([
  "openpcb.core.symbol.passive.resistor",
  "openpcb.core.symbol.passive.capacitor",
]);

/** KLC pin/label text is 1.27 mm. Anything smaller is a pre-KLC leftover. */
const MIN_LABEL_FONT_MM = 1.0;

function coordKey(p: PointMm): string {
  return `${p.x},${p.y}`;
}

/**
 * G1 — the electrical pin array and the preview must describe the same symbol.
 *
 * The app wires from `normalized.pins`, not from the preview, so the two
 * drifting apart is invisible until parts short in a real schematic. KiCad
 * draws every unit of a multi-unit symbol at identical local coordinates, so
 * a preview that only carried unit 1 left the other units' pins coincident —
 * all four LM324 op-amp outputs on (7.62, 0), merged into one net by any
 * coordinate-based net derivation.
 */
function checkPinIntegrity(file: string, data: SymbolSource): void {
  const pins = data.normalized?.pins ?? [];
  const preview = data.normalized?.preview;
  if (pins.length === 0 || !preview?.pins) return;

  // G1a — parity.
  if (pins.length !== preview.pins.length) {
    fail(
      file,
      `symbol preview has ${preview.pins.length} pin(s) but normalized.pins has ${pins.length} — every pin must be represented`,
    );
    return;
  }

  // G1b — the electrical coordinate must equal the drawn anchor.
  const anchors = new Map(
    preview.pins.map((pin) => [pin.id ?? "", pin.anchor]),
  );
  for (const pin of pins) {
    const anchor = anchors.get(pin.originPinKey ?? "");
    if (!anchor || !pin.localPosition) continue;
    if (anchor.x !== pin.localPosition.x || anchor.y !== pin.localPosition.y) {
      fail(
        file,
        `pin ${pin.originPinKey} sits at (${pin.localPosition.x}, ${pin.localPosition.y}) but is drawn at (${anchor.x}, ${anchor.y}) — preview and normalized.pins disagree`,
      );
    }
  }

  const byCoord = new Map<string, typeof pins>();
  for (const pin of pins) {
    if (!pin.localPosition) continue;
    const key = coordKey(pin.localPosition);
    byCoord.set(key, [...(byCoord.get(key) ?? []), pin]);
  }

  for (const [key, stacked] of byCoord) {
    if (stacked.length < 2) continue;

    // G1c — pins of different units sharing a coordinate is the short.
    const units = new Set(stacked.map((pin) => pin.unit ?? 1));
    if (units.size > 1) {
      fail(
        file,
        `pins of different units share coordinate (${key}): ${stacked.map((p) => p.originPinKey).join(", ")} — units must not overlap`,
      );
      continue;
    }

    // G1d — stacking WITHIN a unit is a legitimate KiCad idiom (every GND pad
    // drawn at one point as a single power_in plus N passive duplicates), but
    // only when the pins are the same signal. Differing names would be a real
    // short.
    const names = new Set(stacked.map((pin) => (pin.name ?? "").trim()));
    if (names.size > 1) {
      fail(
        file,
        `pins with different names share coordinate (${key}): ${stacked.map((p) => `${p.originPinKey}=${p.name}`).join(", ")}`,
      );
    }
  }
}

/**
 * G2 — `raw` must be a real parse, not the 2-key placeholder the retired seed
 * importer wrote. Without it an asset cannot be re-normalized offline and
 * silently misses every future preview-builder fix.
 */
function checkRawIntegrity(
  file: string,
  id: string,
  raw: unknown,
  kind: "footprint" | "symbol",
): void {
  if (kind === "symbol" && RAW_EXEMPT_SYMBOLS.has(id)) return;
  const record =
    typeof raw === "object" && raw !== null && !Array.isArray(raw)
      ? (raw as Record<string, unknown>)
      : null;
  const usable =
    record !== null &&
    (kind === "footprint"
      ? Array.isArray(record.pads) && Array.isArray(record.graphics)
      : Array.isArray(record.pins) && Array.isArray(record.bodyGraphics));
  if (!usable) {
    fail(
      file,
      `${kind} has no rebuildable raw parse — run tools/backfill-raw.ts (asset cannot be re-normalized offline)`,
    );
  }
}

/**
 * G3 — courtyard is the keep-out envelope the PCB renderer, the assembly view
 * and the auto-placer's overlap gate all read. `no3d` mechanical parts are
 * exempt only when they genuinely have no body.
 */
function checkCourtyard(file: string, data: FootprintSource): void {
  const graphics = data.normalized?.preview?.graphics ?? [];
  const hasCourtyard = graphics.some((g) =>
    /^[FB]\.(CrtYd|Courtyard)$/.test(g.layer ?? ""),
  );
  if (!hasCourtyard) {
    fail(
      file,
      `footprint preview carries no courtyard geometry (F.CrtYd/B.CrtYd) — required for placement clearance`,
    );
  }
}

/**
 * G4 — protect composed multi-unit symbols from the app's boot-time preview
 * migration.
 *
 * `rebuildPreviewModelsIfStale` (OpenPCB library module) treats ANY preview
 * label with `fontSizeMm < 1.0` as a stale pre-KLC preview and rebuilds it via
 * a source that hardcodes `unitCount: 1` — which would collapse a composed
 * multi-unit symbol back onto a single unit and reintroduce the pin
 * collisions.
 *
 * Sub-1 mm text is NOT stale in itself: KiCad sources legitimately specify
 * smaller per-pin name fonts (LM386 "GAIN", TL081 "NULL") and free body text,
 * and the importer preserves them faithfully. So the gate is scoped to the
 * only case where it does damage — a symbol with more than one unit.
 */
function checkLabelFontSizes(file: string, data: SymbolSource): void {
  const preview = data.normalized?.preview;
  if (!preview || (preview.unitCount ?? 1) <= 1) return;

  for (const label of preview.labels ?? []) {
    if (
      typeof label.fontSizeMm === "number" &&
      label.fontSizeMm < MIN_LABEL_FONT_MM
    ) {
      fail(
        file,
        `multi-unit symbol has preview label "${label.text ?? ""}" at fontSizeMm ${label.fontSizeMm} (< ${MIN_LABEL_FONT_MM}) — the app's stale-preview migration would rebuild it as a single unit and re-stack the pins`,
      );
      return;
    }
  }
}

function setDifference(left: Set<string>, right: Set<string>): string[] {
  return [...left].filter((value) => !right.has(value)).sort();
}

function firstPathSegment(file: string): string | null {
  const rel = displayPath(file);
  const parts = rel.split("/");
  return parts.length >= 3 ? (parts[1] ?? null) : null;
}

function idCategory(id: string, prefix: string): string | null {
  if (!id.startsWith(prefix)) return null;
  return id.slice(prefix.length).split(".")[0] ?? null;
}

function checkCategoryMatchesFile(
  file: string,
  id: string,
  prefix: string,
): void {
  const folder = firstPathSegment(file);
  const category = idCategory(id, prefix);
  if (folder && category && folder !== category) {
    fail(
      file,
      `category folder ${folder} does not match id category ${category}`,
    );
  }
}

function rememberName(
  index: Map<string, string>,
  file: string,
  name: string | undefined,
  kind: string,
): void {
  if (!name) return;
  const normalized = name.trim().toLowerCase();
  if (!normalized) return;
  const hit = index.get(normalized);
  if (hit) warn(file, `duplicate ${kind} name "${name}" (also in ${hit})`);
  else index.set(normalized, displayPath(file));
}

// --- symbols ---
const symbolIds = new Set<string>();
const symbolPinsById = new Map<string, Set<string>>();
const symbolById = new Map<string, GateSymbol>();
const symbolNames = new Map<string, string>();
for (const file of walkFiles(symbolsRoot, ".symbol.json")) {
  const data = loadJson<SymbolSource & { name?: string }>(file);
  if (!validateSymbol(data)) {
    for (const err of validateSymbol.errors ?? [])
      fail(file, `${err.instancePath} ${err.message}`);
    continue;
  }
  checkProvenance(file, data.provenance);
  checkUniqueness(file, data.id, data.uuid);
  checkCategoryMatchesFile(file, data.id, "openpcb.core.symbol.");
  rememberName(symbolNames, file, data.name, "symbol");
  checkDuplicateSymbolPins(file, data);
  checkRawIntegrity(file, data.id, data.raw, "symbol");
  checkPinIntegrity(file, data);
  checkLabelFontSizes(file, data);
  symbolIds.add(data.id);
  symbolPinsById.set(data.id, symbolPinNumbers(data));
  symbolById.set(data.id, data as unknown as GateSymbol);
}

// --- footprints ---
const footprintIds = new Set<string>();
const footprintPadsById = new Map<string, Set<string>>();
const footprintModelRefs: Array<{
  file: string;
  footprintId: string;
  modelIds: string[];
  no3d: boolean;
}> = [];
const footprintHasModels = new Map<string, boolean>();
const footprintNo3d = new Map<string, boolean>();
let no3dCount = 0;
const footprintNames = new Map<string, string>();
for (const file of walkFiles(footprintsRoot, ".fp.json")) {
  const data = loadJson<FootprintSource>(file);
  if (!validateFootprint(data)) {
    for (const err of validateFootprint.errors ?? [])
      fail(file, `${err.instancePath} ${err.message}`);
    continue;
  }
  checkProvenance(file, data.provenance);
  checkUniqueness(file, data.id, data.uuid);
  checkCategoryMatchesFile(file, data.id, "openpcb.core.footprint.");
  rememberName(footprintNames, file, data.name, "footprint");
  checkRawIntegrity(file, data.id, data.raw, "footprint");
  checkCourtyard(file, data);
  reportFindings(file, runFootprintGates(data as unknown as GateFootprint));
  footprintIds.add(data.id);
  footprintPadsById.set(data.id, footprintPadNumbers(data));
  const no3d = data.no3d === true;
  footprintModelRefs.push({
    file,
    footprintId: data.id,
    modelIds: data.models3d ?? [],
    no3d,
  });
  footprintHasModels.set(data.id, (data.models3d ?? []).length > 0);
  footprintNo3d.set(data.id, no3d);
  if (no3d) {
    no3dCount++;
    if ((data.models3d ?? []).length > 0)
      fail(file, `no3d footprint must not reference a 3d model: ${data.id}`);
  }
}

// --- models3d ---
const modelIds = new Set<string>();
const modelFormatPaths = new Set<string>();
for (const file of walkFiles(modelsRoot, ".model.json")) {
  const data = loadJson<{
    id: string;
    uuid: string;
    provenance: Provenance;
    formats: Record<string, { path: string; sha256: string }>;
  }>(file);
  if (!validateModel3d(data)) {
    for (const err of validateModel3d.errors ?? [])
      fail(file, `${err.instancePath} ${err.message}`);
    continue;
  }
  checkProvenance(file, data.provenance);
  checkUniqueness(file, data.id, data.uuid);
  checkCategoryMatchesFile(file, data.id, "openpcb.core.3d.");
  modelIds.add(data.id);
  if (REQUIRE_STEP_3D && !data.formats.step)
    fail(file, "release validation requires a STEP format");
  for (const [fmt, info] of Object.entries(data.formats)) {
    if (modelFormatPaths.has(info.path))
      warn(file, `duplicate 3d asset path: ${info.path}`);
    modelFormatPaths.add(info.path);
    if (!info.path.startsWith("3d/"))
      fail(file, `${fmt} asset path must stay under 3d/: ${info.path}`);
    const abs = path.join(LIBRARY_ROOT, info.path);
    if (!existsSync(abs)) {
      fail(file, `${fmt} asset missing: ${info.path}`);
    } else if (sha256File(abs) !== info.sha256) {
      fail(file, `${fmt} sha256 mismatch: ${info.path}`);
    }
  }
}

for (const ref of footprintModelRefs) {
  if (REQUIRE_STEP_3D && !ref.no3d && ref.modelIds.length === 0) {
    fail(
      ref.file,
      `release validation requires at least one STEP-backed 3d model on ${ref.footprintId}`,
    );
  }
  if (REQUIRE_STEP_3D && !ref.no3d && ref.modelIds.length !== 1) {
    fail(
      ref.file,
      `release validation requires exactly one 3d model on ${ref.footprintId}`,
    );
  }
  for (const modelId of ref.modelIds) {
    if (!modelIds.has(modelId))
      fail(ref.file, `unknown 3d model ref on ${ref.footprintId}: ${modelId}`);
  }
}

// --- components ---
const componentNames = new Map<string, string>();
const componentAliases = new Map<string, string>();
const referencedFootprints = new Set<string>();
const gateCheckedSymbols = new Set<string>();
for (const file of walkFiles(componentsRoot, ".component.json")) {
  const data = loadJson<
    GateComponent & {
      uuid: string;
      name?: string;
      subcategory?: string;
      tags?: string[];
      aliases?: string[];
      datasheetSource?: string;
      defaultFootprint: string;
      provenance: Provenance;
      footprints: Array<{
        footprint: string;
        pinMap?: PinMapEntry[];
      }>;
    }
  >(file);
  if (!validateComponent(data)) {
    for (const err of validateComponent.errors ?? [])
      fail(file, `${err.instancePath} ${err.message}`);
    continue;
  }
  checkProvenance(file, data.provenance);
  checkUniqueness(file, data.id, data.uuid);
  checkCategoryMatchesFile(file, data.id, "openpcb.core.");
  if (data.category && firstPathSegment(file) !== data.category)
    fail(
      file,
      `category field ${data.category} does not match folder ${firstPathSegment(file)}`,
    );
  rememberName(componentNames, file, data.name, "component");
  for (const alias of data.aliases ?? [])
    rememberName(componentAliases, file, alias, "component alias");
  if (data.category && !(data.tags ?? []).includes(data.category))
    warn(file, `tags should include category "${data.category}"`);
  if (
    typeof data.datasheet === "string" &&
    data.datasheet.length > 0 &&
    !isHttpUri(data.datasheet)
  )
    fail(file, `datasheet must be an http(s) URL: ${data.datasheet}`);
  if (data.datasheetSource !== undefined && !isHttpUri(data.datasheetSource))
    fail(
      file,
      `datasheetSource must be an http(s) URL: ${data.datasheetSource}`,
    );
  // G5 — parameters must use the canonical vocabulary. Free-form keys made the
  // field unusable for search or filtering: 95 distinct spellings across 155
  // components, with vrrm/reverse_voltage and vce/vce_max both in play.
  if (data.category && data.parameters) {
    const unknown = unknownParameterKeys(data.category, data.parameters);
    if (unknown.length > 0) {
      fail(
        file,
        `unknown parameter key(s) for category '${data.category}': ${unknown.join(", ")} — see docs/PARAMETERS.md (add to tools/parameter-dictionary.ts if legitimate)`,
      );
    }
  }

  // G6 (required headline parameters), G7 (sourcing), G8 (datasheet ↔
  // manufacturer), G9 (symbol ERC on the owning component's symbol).
  reportFindings(
    file,
    runComponentGates(data, symbolById.get(data.symbol), gateCheckedSymbols),
  );
  const symbolPins = symbolPinsById.get(data.symbol);
  if (!symbolIds.has(data.symbol))
    fail(file, `unknown symbol ref: ${data.symbol}`);
  const variantFps = new Set(data.footprints.map((v) => v.footprint));
  if (!variantFps.has(data.defaultFootprint))
    fail(file, `defaultFootprint ${data.defaultFootprint} not in footprints[]`);
  for (const v of data.footprints) {
    referencedFootprints.add(v.footprint);
    const footprintPads = footprintPadsById.get(v.footprint);
    if (!footprintIds.has(v.footprint))
      fail(file, `unknown footprint ref: ${v.footprint}`);
    if (
      REQUIRE_STEP_3D &&
      !footprintNo3d.get(v.footprint) &&
      !footprintHasModels.get(v.footprint)
    )
      fail(
        file,
        `release validation requires STEP-backed 3d model for footprint ${v.footprint}`,
      );
    if (!symbolPins || !footprintPads) continue;

    const pinMap = v.pinMap ?? [];
    if (pinMap.length === 0 && symbolPins.size > 0) {
      fail(file, `missing pinMap for footprint ${v.footprint}`);
      continue;
    }

    const mappedPins = new Set<string>();
    const mappedPads = new Set<string>();
    for (const entry of pinMap) {
      mappedPins.add(entry.pinNumber);
      mappedPads.add(entry.padNumber);
      if (!symbolPins.has(entry.pinNumber))
        fail(
          file,
          `pinMap references unknown symbol pin ${entry.pinNumber} for footprint ${v.footprint}`,
        );
      if (!footprintPads.has(entry.padNumber))
        fail(
          file,
          `pinMap references unknown footprint pad ${entry.padNumber} for footprint ${v.footprint}`,
        );
    }

    const unmappedPins = setDifference(symbolPins, mappedPins);
    if (unmappedPins.length > 0)
      fail(
        file,
        `pinMap for footprint ${v.footprint} does not map symbol pin(s): ${unmappedPins.join(", ")}`,
      );

    const unmappedPads = setDifference(footprintPads, mappedPads);
    if (unmappedPads.length > 0)
      warn(
        file,
        `pinMap for footprint ${v.footprint} does not map footprint pad(s): ${unmappedPads.join(", ")}`,
      );
  }
}

for (const footprintId of footprintIds) {
  if (!referencedFootprints.has(footprintId))
    warnDisplay(
      idIndex.get(footprintId) ?? "<unknown>",
      `footprint is not referenced by any component: ${footprintId}`,
    );
}

if (issues.length === 0) {
  for (const warning of warnings)
    console.warn(`  ${warning.file}: ${warning.message}`);
  const no3dSuffix =
    no3dCount > 0
      ? ` (${no3dCount} footprint(s) no3d — excluded from STEP gate)`
      : "";
  console.log(
    `[validate] OK — ${symbolIds.size} symbols, ${footprintIds.size} footprints, ${modelIds.size} 3d models, ${idIndex.size - symbolIds.size - footprintIds.size - modelIds.size} components${no3dSuffix}`,
  );
  process.exit(0);
}

console.error(`[validate] ${issues.length} issue(s):`);
for (const issue of issues) console.error(`  ${issue.file}: ${issue.message}`);
process.exit(1);
